# STAT206 HW2 - Winter 2023

Name: _INSERT_YOUR_NAME_

---
# Homework \#2 instructions

**Review lecture notes on Numpy basics before answering the homework questions.**

For this homework, use the Python built-in functions, as well as the `numpy`, `scipy`, and `matplotlib` packages to answer the questions. **DO NOT** use `pandas`.

Replace **INSERT_YOUR_ANSWER** with your own code or text answers.

Please comment your Python code thoroughly. Please follow the Python coding style guidelines (https://google.github.io/styleguide/pyguide.html or https://www.python.org/dev/peps/pep-0008/).
**Partial credit will be deducted for insufficient commenting or poor coding styles.**

If you have any question about this homework assignment, please post it on [**Piazza**](http://piazza.com/ucr/winter2023/stat206/home).

---

## Homework submission guideline

- Late submission penalties.  
    - Submissions up to 24 hours late will incur a 10% deduction.
    - Submissions up to 48 hours late will incur a 20% deduction.
    - No submission will be accepted after 2 days past the initial deadline.
    - **If you are using your free late days, please state here: INSERT_YOUR_ANSWER**

- After you complete all questions, save your `ipynb` file to `FirstnameLastname-SID-HW2.ipynb`. Then print out your answer (Jupyter Menu File->Download as, or Colab Menu File->Print), and save to a `pdf` file `FirstnameLastname-SID-HW2.pdf`.

- Submit **BOTH your source `ipynb` file and the printed `pdf` file** to **GradeScope**. You can submit multiple times, you last submission will be graded. For the `pdf` submission, please **tag specific pages** that correspond with each question in the assignment.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize

---
# &diams; Question 1: Matrix scaling/normalization [20 pts]

(a) Create the following 5x4 numpy array, and save it as `x`.
```
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]
 [0. 0. 5. 0.]]
 ```

In [ ]:
# INSERT_YOUR_ANSWER


---
(b) Scale the matrix by row, so that all rows have mean 0 and standard deviation 1. Save the scaled matrix as `x_scaled`.

**Hint**: Substract each row by its mean and then divided by its standard deviation.

The expected result is 
```
[[ 1.73205081 -0.57735027 -0.57735027 -0.57735027]
 [-0.57735027  1.73205081 -0.57735027 -0.57735027]
 [-0.57735027 -0.57735027  1.73205081 -0.57735027]
 [-0.57735027 -0.57735027 -0.57735027  1.73205081]
 [-0.57735027 -0.57735027  1.73205081 -0.57735027]]
 ```

In [ ]:
# INSERT_YOUR_ANSWER


In [ ]:
# testing
print(np.around(x_scaled.mean(axis=1)))
print(x_scaled.std(axis=1))

---
(c) Scale the matrix by column, so that all columns have mean 0 and standard deviation 1. Save the scaled matrix as `x_scaled2`.

**Hint**: Substract each column by its mean and then divided by its standard deviation.

The expected result is 
```
[[ 2.         -0.5        -0.77702869 -0.5       ]
 [-0.5         2.         -0.77702869 -0.5       ]
 [-0.5        -0.5         0.6799001  -0.5       ]
 [-0.5        -0.5        -0.77702869  2.        ]
 [-0.5        -0.5         1.65118597 -0.5       ]]
 ```

In [ ]:
# INSERT_YOUR_ANSWER


In [ ]:
# testing
print(np.around(x_scaled2.mean(axis=0)))
print(x_scaled2.std(axis=0))

---

# &diams; Question 2: Plotting the iris data with `matplotlib` [20 pts]

Description of the iris dataset: https://archive.ics.uci.edu/ml/datasets/iris

First, let's load the iris data as a numpy array `iris`. The four columns are  'sepal_length', 'sepal_width', 'petal_length', and 'petal_width', correspondingly.


In [ ]:
from sklearn import datasets
iris = datasets.load_iris().data
print(type(iris))
print(iris.shape)

Use `matplotlib` to plot the following figures.

---
(a) Draw four boxplots side by side, one for each column in the iris data.

Add proper axis labels, a title, etc.

Use `xticks` to set the labels as 'sepal_length', 'sepal_width', 'petal_length', and 'petal_width'.

In [ ]:
# INSERT_YOUR_ANSWER


---
(b) Draw one histogram of every column in the iris data. Display them in a 2-by-2 layout. Set the x-axis labels of the subplot as 'sepal_length', 'sepal_width', 'petal_length', and 'petal_width', correspondingly.

**Hint**: Use `matplotlib.pyplot.subplot()`


In [ ]:
# INSERT_YOUR_ANSWER


---
(c) Suppose we assume that the `sepal_width` variable follows a Normal distribution. Estimate the mean and standard deviation using `np.mean()` and `np.std()`.

Plot the estimated normal curve in red color on top of the histogram of `sepal_width`.

Add proper axis labels, a title, etc.

**Hint**: 1) Use `norm.pdf()` in `scipy.stats.norm`; 2) Plot the density histogram instead of the default frequency histogram.

In [ ]:
# INSERT_YOUR_ANSWER
from scipy.stats import norm


---
# &diams; Question 3: Optimization [20 pts]

(a) Use `matplotlib` to plot the function over the interval [-3, 3]. 
$$f(x) = sin^2(x − 2)e^{−x^2}$$
Add proper axis labels, a title, etc.

**Hint**: Use `numpy.sin()` and `numpy.exp()`




In [ ]:
# INSERT_YOUR_ANSWER 


---
(b) Find the maximum of the function.

**Hint**: 1) Maximizing a function f(x) is equivalent to minimizing -f(x); 2) Use `scipy.optimize.minimize()`.

The expected results is 0.21624139


In [ ]:
# INSERT_YOUR_ANSWER 


---
(c) Draw the function again and highlight the maximal point as a green circle.

In [ ]:
# INSERT_YOUR_ANSWER 


---
# &diams; Question 4: Simulation of least squares regression [40 pts]

(a) Sample generation

Write your own code to simulate 100 data points from the following model.

$$X \sim Uniform(A=-2, B=2)$$
$$\epsilon \sim N(\mu=0,\sigma=2)$$
$$Y=2+3X+\epsilon$$

**Hint**: Use `numpy.random.uniform()` and `numpy.random.normal()`.

Using the random seed of 206 (for both $X$ and $\epsilon$), you are expected to get the following numpy arrays:

`X = [-0.29070303 -0.06043533 ... -0.4816969   0.91843692]`

`Y = [3.44303672e-03 -3.59006976e+00 ... 1.80521284e+00  4.29317228e+00]`

In [ ]:
# INSERT_YOUR_ANSWER


---
(b) Use `matplotlib` to draw a scatter plot of the 100 data points $(x_0, y_0), \cdots, (x_{100}, y_{100})$. Add the polulation regression line $Y=2+3X$ in red color.

Add proper axis labels, a title, etc.

In [ ]:
# INSERT_YOUR_ANSWER


---
(c) Use `scipy.optimize.curve_fit()` to fit a least squares regression $Y = \beta_0 + \beta_1 X$ to the simulated data.

The expected estimates are $\hat{\beta_0}$=1.8914943777278204 and $\hat{\beta_1}$=2.87327463881861.


In [ ]:
# INSERT_YOUR_ANSWER


---
(d) Luckily, we have the analytical solution of the least squares regression $Y = \beta_0 + \beta_1 X + \epsilon$, which is

$$ 
\begin{aligned}
 \hat{\beta_1} & = 
 \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}
 {\sum_{i=1}^{n} (x_i - \bar{x})^2} \\
 \hat{\beta_0} & = \bar{y} - \hat{\beta_1} \bar{x}
\end{aligned} 
$$

Write your own code to calculate $\hat{\beta_0}$ and $\hat{\beta_1}$ using the above equations. Compare your results with the coefficients calculated by the `scipy.optimize.curve_fit()` function in part (c). Are they the same?

The expected results are $\hat{\beta_0}$=1.8914943756627591 and $\hat{\beta_1}$=2.8732746405232445.

In [ ]:
# INSERT_YOUR_ANSWER


---
(e) Redraw a scatter plot of the 100 data points $(x_0, y_0), \cdots, (x_{100}, y_{100})$. Add the polulation regression line $Y=2+3X$ in red color. Add the least squares fitted line, using the coefficients estimated in part (d), in blue color.

Add proper axis labels, a title, etc.

In [ ]:
# INSERT_YOUR_ANSWER


---
(f) Recall in part (a), we set the random seed to be 206. 
This time, without fixing the random seeds, repeat the simulation 10 times and draw the 10 least sqaure regression lines (one for each simulation) on the same plot. Also, add the polulation regression line  $𝑌=2+3𝑋$  in red color. Note that you do not need to draw the individual data points.

Add proper axis labels, a title, etc.

In [ ]:
# INSERT_YOUR_ANSWER
